# Drugs Classification (Logistic Regression)

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('drug200.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[23 'F' 'HIGH' 'HIGH' 25.355]
 [47 'M' 'LOW' 'HIGH' 13.093]
 [47 'M' 'LOW' 'HIGH' 10.114]
 [28 'F' 'NORMAL' 'HIGH' 7.798]
 [61 'F' 'LOW' 'HIGH' 18.043]
 [22 'F' 'NORMAL' 'HIGH' 8.607]
 [49 'F' 'NORMAL' 'HIGH' 16.275]
 [41 'M' 'LOW' 'HIGH' 11.037]
 [60 'M' 'NORMAL' 'HIGH' 15.171]
 [43 'M' 'LOW' 'NORMAL' 19.368]
 [47 'F' 'LOW' 'HIGH' 11.767]
 [34 'F' 'HIGH' 'NORMAL' 19.199]
 [43 'M' 'LOW' 'HIGH' 15.376]
 [74 'F' 'LOW' 'HIGH' 20.942]
 [50 'F' 'NORMAL' 'HIGH' 12.703]
 [16 'F' 'HIGH' 'NORMAL' 15.516]
 [69 'M' 'LOW' 'NORMAL' 11.455]
 [43 'M' 'HIGH' 'HIGH' 13.972]
 [23 'M' 'LOW' 'HIGH' 7.298]
 [32 'F' 'HIGH' 'NORMAL' 25.974]
 [57 'M' 'LOW' 'NORMAL' 19.128]
 [63 'M' 'NORMAL' 'HIGH' 25.917]
 [47 'M' 'LOW' 'NORMAL' 30.568]
 [48 'F' 'LOW' 'HIGH' 15.036]
 [33 'F' 'LOW' 'HIGH' 33.486]
 [28 'F' 'HIGH' 'NORMAL' 18.809]
 [31 'M' 'HIGH' 'HIGH' 30.366]
 [49 'F' 'NORMAL' 'NORMAL' 9.381]
 [39 'F' 'LOW' 'NORMAL' 22.697]
 [45 'M' 'LOW' 'HIGH' 17.951]
 [18 'F' 'NORMAL' 'NORMAL' 8.75]
 [74 'M' 'HIGH' 'HIGH' 

In [5]:
print(y)

['DrugY' 'drugC' 'drugC' 'drugX' 'DrugY' 'drugX' 'DrugY' 'drugC' 'DrugY'
 'DrugY' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'drugX' 'drugA'
 'drugC' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'drugX' 'drugB' 'drugX' 'DrugY' 'drugX' 'drugX'
 'drugA' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugB' 'DrugY' 'drugX' 'drugX'
 'drugX' 'drugA' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY'
 'drugB' 'drugC' 'drugB' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'drugA' 'DrugY'
 'drugX' 'drugB' 'DrugY' 'drugA' 'drugX' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'DrugY' 'drugA' 'DrugY' 'drugA' 'drugX' 'drugB'
 'drugX' 'drugC' 'drugA' 'drugC' 'drugB' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'drugA' 'drugA' 'drugC' 'drugX' 'DrugY' 'drugX' 'drugX' 'DrugY'
 'drugB' 'DrugY' 'drugA' 'drugX' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugX'
 'drugX' 'drugA' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'D

## One Hot Encoding and Label Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
X[:, 1] = le.fit_transform(X[:, 1])
X[:, 2] = le.fit_transform(X[:, 2])
X[:, 3] = le.fit_transform(X[:, 3])

In [15]:
print(X)

[[23 0 0 0 25.355]
 [47 1 1 0 13.093]
 [47 1 1 0 10.114]
 [28 0 2 0 7.798]
 [61 0 1 0 18.043]
 [22 0 2 0 8.607]
 [49 0 2 0 16.275]
 [41 1 1 0 11.037]
 [60 1 2 0 15.171]
 [43 1 1 1 19.368]
 [47 0 1 0 11.767]
 [34 0 0 1 19.199]
 [43 1 1 0 15.376]
 [74 0 1 0 20.942]
 [50 0 2 0 12.703]
 [16 0 0 1 15.516]
 [69 1 1 1 11.455]
 [43 1 0 0 13.972]
 [23 1 1 0 7.298]
 [32 0 0 1 25.974]
 [57 1 1 1 19.128]
 [63 1 2 0 25.917]
 [47 1 1 1 30.568]
 [48 0 1 0 15.036]
 [33 0 1 0 33.486]
 [28 0 0 1 18.809]
 [31 1 0 0 30.366]
 [49 0 2 1 9.381]
 [39 0 1 1 22.697]
 [45 1 1 0 17.951]
 [18 0 2 1 8.75]
 [74 1 0 0 9.567]
 [49 1 1 1 11.014]
 [65 0 0 1 31.876]
 [53 1 2 0 14.133]
 [46 1 2 1 7.285]
 [32 1 0 1 9.445]
 [39 1 1 1 13.938]
 [39 0 2 1 9.709]
 [15 1 2 0 9.084]
 [73 0 2 0 19.221]
 [58 0 0 1 14.239]
 [50 1 2 1 15.79]
 [23 1 2 0 12.26]
 [50 0 2 1 12.295]
 [66 0 2 1 8.107]
 [37 0 0 0 13.091]
 [68 1 1 0 10.291]
 [23 1 2 0 31.686]
 [28 0 1 0 19.796]
 [58 0 0 0 19.416]
 [67 1 2 1 10.898]
 [62 1 1 1 27.183]
 [24 0 

In [16]:
print(y)

[0 3 3 4 0 4 0 3 0 0 3 0 0 0 4 0 4 1 3 0 0 0 0 0 0 0 0 4 0 0 4 2 4 0 4 4 1
 4 4 4 0 2 0 4 4 4 1 3 0 0 0 4 0 0 2 3 2 0 4 0 0 1 0 4 2 0 1 4 0 0 2 0 4 0
 0 0 1 0 1 4 2 4 3 1 3 2 4 0 0 0 0 0 0 0 0 4 0 0 0 0 1 1 3 4 0 4 4 0 2 0 1
 4 4 4 4 0 4 4 1 0 0 0 0 0 2 0 0 4 0 4 0 0 4 0 0 4 2 1 2 4 1 0 2 0 1 4 4 1
 4 3 1 2 4 4 0 3 1 0 3 4 4 2 4 0 0 0 0 4 0 1 4 4 0 0 1 0 1 0 0 0 0 4 4 0 0
 0 2 1 0 0 0 1 0 3 0 3 3 4 4 4]


## Spliting dataset to train and test data

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [26]:
print(len(X_train))

160


In [19]:
print(len(X_test))

40


In [20]:
print(len(y_train))

160


In [21]:
print(len(y_test))

40


## Feature Scaling

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, [0, 4]] = sc.fit_transform(X_train[:, [0, 4]])
X_test[:, [0, 4]] = sc.fit_transform(X_test[:, [0, 4]])

In [28]:
print(X_train)

[[-1.4041592110838836 1 0 1 1.8498131594492802]
 [-0.7893111712004097 0 0 1 1.5120348327367668]
 [1.6700809883334864 1 1 0 -1.2840999795536738]
 [0.00999128064810654 1 1 1 -0.811210322156155]
 [1.7315657923218337 0 2 0 0.5288378326119375]
 [-0.6048567592353675 1 2 1 -1.1274407211301116]
 [1.6700809883334864 1 1 0 0.1050133890515378]
 [1.0552329484500125 1 1 1 1.6880581073037617]
 [-1.6500984270372734 0 2 1 -0.995678054890963]
 [0.686324124519928 0 0 0 1.4277358451649798]
 [0.44038490856653834 1 2 0 -0.8291183972361718]
 [-1.6500984270372734 0 0 1 1.2648160401687287]
 [-1.0352503871537992 0 0 1 0.46885306079919814]
 [-1.3426744070955363 1 2 0 -0.48464274163194465]
 [-1.6500984270372734 0 0 0 3.144727141251477]
 [0.13296088862480135 1 0 0 -0.755010997108297]
 [0.25593049660149614 1 0 1 -1.002957760208043]
 [0.3174153005898436 0 2 1 0.23619367886531994]
 [0.3174153005898436 0 2 0 -0.4201445525226156]
 [1.4241417723800969 1 1 0 -0.7713175370185563]
 [0.07147608463645394 1 2 1 -1.2089734206

In [29]:
print(X_test)

[[-1.5187291826161147 1 0 1 0.11563502591981223]
 [-0.5342336209583854 0 1 0 1.8977788193075638]
 [-0.7658796354660864 1 0 0 -0.6414591430924169]
 [-1.0554371536007126 1 2 0 0.9500264048393212]
 [1.8401380277455495 1 0 0 -1.0462848172724235]
 [-0.4763221173314602 1 2 0 0.5401542567640938]
 [1.724315020491699 1 0 1 -1.0327454970657344]
 [-0.3604991100776097 0 0 0 -0.8455336240259683]
 [-0.12885309556990876 1 0 0 1.2011192523088297]
 [0.8556424660878204 0 2 1 0.9631964708585552]
 [-0.186764599196834 1 2 0 -0.258296381243113]
 [-1.344994671735339 0 0 1 0.9725509102740859]
 [0.9135539697147457 0 0 1 -0.47123296267558823]
 [0.5660849479531942 1 1 1 1.8283590320659937]
 [-0.650056628212236 1 0 0 1.513754464354198]
 [-0.07094159194298351 0 1 1 0.08264831850715121]
 [1.3189344951032222 0 0 1 1.6996124053732953]
 [-1.2870831681084136 1 0 1 2.1627802411712174]
 [-0.3604991100776097 0 2 0 -0.16179795358816454]
 [-0.5921451245853107 1 0 1 -1.0613011542289332]
 [-1.344994671735339 0 0 0 -0.58520942

## Data Fitting and Model Creation

In [30]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Prediction

In [31]:
y_pred = classifier.predict(X_test)

In [32]:
print(y_pred)

[0 0 1 0 2 0 2 1 0 0 4 0 2 0 0 0 0 0 4 1 1 1 4 2 2 0 4 2 3 4 0 4 4 1 2 3 0
 4 4 0]


## Metrics

In [44]:
from sklearn.metrics import multilabel_confusion_matrix
mlc = multilabel_confusion_matrix(y_test, y_pred)
print(mlc)

[[[18  0]
  [ 6 16]]

 [[34  1]
  [ 0  5]]

 [[33  2]
  [ 0  5]]

 [[38  0]
  [ 0  2]]

 [[31  3]
  [ 0  6]]]


In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred) * 100

85.0